# Canonical X12 856 TOML
# Freight Trust & Clearing
# MIT License

header = [
  "01",
  "0000000000",
  "01",
  "ABCCO     ",
  "12",
  "4405197800     ",
  "01",
  "999999999      ",
  "111206",
  "1719",
  "-",
  "00406",
  "000000049",
  "0",
  "P",
  ">"
]

[options]
segmentTerminator = "~"
elementDelimiter = "*"
endOfLine = "\n"
format = false
subElementDelimiter = ">"

[[functionalGroups]]
header = [
  "SH",
  "4405197800",
  "999999999",
  "20111206",
  "1045",
  "49",
  "X",
  "004060"
]

  [[functionalGroups.transactions]]
  header = [
    "856",
    "0008"
  ]

    [[functionalGroups.transactions.segments]]
    tag = "BSN"
    elements = [
      "14",
      "829716",
      "20111206",
      "142428",
      "0002"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "HL"
    elements = [
      "1",
      "",
      "S"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "TD1"
    elements = [
      "PCS",
      "2",
      "",
      "",
      "",
      "A3",
      "60.310",
      "LB"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "TD5"
    elements = [
      "",
      "2",
      "XXXX",
      "",
      "XXXX"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "REF"
    elements = [
      "BM",
      "999999-001"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "REF"
    elements = [
      "CN",
      "5787970539"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "DTM"
    elements = [
      "011",
      "20111206"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "N1"
    elements = [
      "SH",
      "1 EDI SOURCE"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "N3"
    elements = [
      "31875 SOLON RD"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "N4"
    elements = [
      "SOLON",
      "OH",
      "44139"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "N1"
    elements = [
      "OB",
      "XYZ RETAIL"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "N3"
    elements = [
      "P O BOX 9999999"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "N4"
    elements = [
      "ATLANTA",
      "GA",
      "31139-0020",
      "",
      "SN",
      "9999"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "N1"
    elements = [
      "SF",
      "1 EDI SOURCE"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "N3"
    elements = [
      "31875 SOLON ROAD"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "N4"
    elements = [
      "SOLON",
      "OH",
      "44139"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "HL"
    elements = [
      "2",
      "1",
      "O"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "PRF"
    elements = [
      "99999817",
      "",
      "",
      "20111205"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "HL"
    elements = [
      "3",
      "2",
      "I"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "LIN"
    elements = [
      "1",
      "VP",
      "87787D",
      "UP",
      "999999310145"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "SN1"
    elements = [
      "1",
      "24",
      "EA"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "PO4"
    elements = [
      "1",
      "24",
      "EA"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "PID"
    elements = [
      "F",
      "",
      "",
      "",
      "BLUE WIDGET"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "HL"
    elements = [
      "4",
      "2",
      "I"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "LIN"
    elements = [
      "2",
      "VP",
      "99887D",
      "UP",
      "999999311746"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "SN1"
    elements = [
      "2",
      "6",
      "EA"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "PO4"
    elements = [
      "1",
      "6",
      "EA"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "PID"
    elements = [
      "F",
      "",
      "",
      "",
      "RED WIDGET"
    ]

    [[functionalGroups.transactions.segments]]
    tag = "CTT"
    elements = [
      "4",
      "30"
    ]